### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by nrgapple** [dovedevic/CMPSC473-ThreadSchedulingTestBenches#1]
You may not have permission to access CMPSC473-ThreadSchedulingTestBenches. Check Preferences to make sure you’re still logged in.

Keep getting this error when I try to Publish my commits to my branch

**Comment by dovedevic** [comment]
Right, forgot to change the setting for changes available to the public. Changed, and fixed. You should be able to branch now.

**Comment by dovedevic** [comment]
Just verified on a separate account you can now branch. Let me know if you encounter any more issues!
